### ISSUE TITLE
非常喜欢您的作品，安装过程中遇到了困难，能否指点一下

### ISSUE THREAD

**Issue by ghost** [aiokr/hexo-theme-type#1]
```
C:\Users\wf09\Desktop\blog\hexo-theme-type\blog\themes\hexo-theme-type\layout\_partial\footer.ejs:36
    34|         <div class="mdui-typo-body-1">
    35|             <%= __('footer.countTotal') %>
 >> 36|           <%- symbolsCountTotal(site) %>
    37|         </div>
    38|         <% } %>
    39|         <% if (theme.busuanzi == true){ %>

symbolsCountTotal is not defined
```

执行hexo -g 和hexo -s命令不成功，老是出现这个问题。我没有修改过您主题的配置文件。不知道哪里出现了问题。我是在这里安装的：https://github.com/aiokr/hexo-theme-type/releases
使用hexo默认的网站配置文件。按照您说的也添加了如下代码：
```
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
  
```
期待您的指点，谢谢！
